import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CodeIndex } from "./indexer.js";

const ws = join(tmpdir(), `cgml-${Date.now()}`);
mkdirSync(join(ws, "a"), { recursive: true }); mkdirSync(join(ws, "b")); mkdirSync(join(ws, "c"));
writeFileSync(join(ws, "a", "m.py"), "import os\nclass Repo:\n    def load(self):\n        return helper()\n\ndef helper():\n    return os.path\n\ndef main():\n    r = Repo()\n    r.load()\n");
writeFileSync(join(ws, "b", "m.go"), "package a\n\nfunc Helper() int { return 1 }\n\nfunc Run() int {\n\th := Helper()\n\treturn h\n}\n");
writeFileSync(join(ws, "c", "m.rs"), "pub fn helper() -> i32 { 1 }\n\npub struct Widget;\n\nimpl Widget {\n    pub fn run(&self) -> i32 {\n        helper()\n    }\n}\n");
const index = new CodeIndex(ws, join(ws, "idx.json"));
const init = await index.initialize();
console.log(`files=${init.files}`);
console.log("py explore Repo:", index.lookupSymbol("Repo").map((h) => h.symbol.kind).join(","));
console.log("py callers of helper:", index.callersOf("helper").map((c) => `${c.file.split("/").pop()}:${c.line} in ${c.caller}`).join(" | "));
console.log("go callees of Run:", index.calleesOf("Run").map((c) => c.callee).join(","));
console.log("rust explore Widget:", index.lookupSymbol("Widget").map((h) => `${h.symbol.kind}@${h.file.split("/").pop()}:${h.symbol.line}`).join(","));
console.log("rust callers of helper:", index.callersOf("helper").map((c) => `${c.file.split("/").pop()}:${c.line} in ${c.caller}`).join(" | "));
rmSync(ws, { recursive: true, force: true });
process.exit(0);
